### ISSUE TITLE
Just Want To Ask

### ISSUE THREAD

**Issue by jfullstackdev** [toffeegz/user-role-permission#2]
hello there, I did the same exam

this might be too much but how was the exam ? 

as for me, I created two standalone apps, as per instruction, I should create endpoints, so I need to separate them

**Comment by toffeegz** [comment]
@jdevstatic hi yes, I passed the exam, 

![image](https://user-images.githubusercontent.com/77222425/181725637-6300c4b0-e908-4c48-a80f-e07c03f718a6.png)

**Comment by toffeegz** [comment]
Hello, Yes I passed the exam,
![image](https://user-images.githubusercontent.com/77222425/181726060-f21ee5cb-e51d-4230-8230-6c7731b604c4.png)
![image](https://user-images.githubusercontent.com/77222425/181726304-d88440c7-2752-4719-a790-bec52b81e2fb.png)

**Comment by jfullstackdev** [comment]
thanks for the info and reply

**Comment by toffeegz** [comment]
> thanks for the info and reply

medyo nahirapan lang po ako since first time ko sa vue and ts,
tall stack dev po kasi ako e, and eto po yung repo nung una kong gawa na hinid po naka endpoint
pero overall goods nmn po, nakakakaba lang po sa tech interview, may mga itatanong lang po kung may idea sa gamit nila

**Comment by toffeegz** [comment]
> > thanks for the info and reply
> 
> medyo nahirapan lang po ako since first time ko sa vue and ts, tall stack dev po kasi ako e, and eto po yung repo nung una kong gawa na hinid po naka endpoint pero overall goods nmn po, nakakakaba lang po sa tech interview, may mga itatanong lang po kung may idea sa gamit nila

sa redcore din po ba kayo nag apply?

**Comment by jfullstackdev** [comment]
oo pero tapos na hehe medyo iba ung ginawa ko, hindi yata nila nagustuhan, pinaghiwalay ko ung mismong sa API lang sila mag interact, ung app ng Vue, ang sa Laravel, ung mismong endpoints

**Comment by toffeegz** [comment]
> oo pero tapos na hehe medyo iba ung ginawa ko, hindi yata nila nagustuhan, pinaghiwalay ko ung mismong sa API lang sila mag interact, ung app ng Vue, ang sa Laravel, ung mismong endpoints

![image](https://user-images.githubusercontent.com/77222425/181728724-37fb0ba6-a01d-42b3-bc7d-8d929281ee6f.png)
tama naman po nakabukod ung api sa client, since sabi api endpoint,
kailan po tech interview niyo? kanina po? kung nasagot niyo nmn po yung mga tanong goods na po yun
tanggap po kayo dyan, tiwala lang po 👍
